version: "3.8"

# 网络配置
networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.5.0/24

# 服务容器配置
services:
  golang:
    build: ./
    environment:
      - TZ=${TZ}
    privileged: true
    volumes:
      - ${CODE_PATH_HOST}:/usr/src/code
    stdin_open: true
    tty: true
    networks:
      backend:
        ipv4_address: 192.168.5.101
    restart: always

  mysql:
    image: mysql:5.7
    environment:
      - TZ=${TZ}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    privileged: true
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      backend:
        ipv4_address: 192.168.5.102
    restart: always

  mysql-manage:
    image: phpmyadmin/phpmyadmin
    environment:
      - TZ=${TZ}
      - PMA_ARBITRARY=1
      - MYSQL_USER=${MYSQL_MANAGE_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_MANAGE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_MANAGE_ROOT_PASSWORD}
      - PMA_HOST=${MYSQL_MANAGE_CONNECT_HOST}
      - PMA_PORT=${MYSQL_MANAGE_CONNECT_PORT}
    ports:
      - "${MYSQL_MANAGE_PORT}:80"
    # 依赖容器 在 Mysql 服务容器启动后启动
    depends_on:
      - mysql
    networks:
      backend:
        ipv4_address: 192.168.5.103
    restart: always

  consul:
    image: consul:1.12
    environment:
      - TZ=${TZ}
      - ALLOW_NONE_AUTHENTICATION=yes
      - CONSUL_ADVERTISE_CLIENT_URLS=http://consul:8500
    ports:
      - "${CONSUL_PORT}:8500"
    networks:
      backend:
        ipv4_address: 192.168.5.104
    restart: always
