version: '3.5'
# 网络配置
networks:
  backend:
    driver: ${NETWORKS_DRIVER}

# 服务容器配置
services:
  golang:
    build: .
    environment:
      - TZ=${TZ}
    privileged: true
    # 挂载到 /usr/src/code 目录
    volumes:
      - ${CODE_PATH_HOST}:/usr/src/code
    ports:
      - "${WEB_SERVER_PORT}:8080"
    stdin_open: true
    tty: true
    networks:
      - backend
    restart: always

  mysql:
    image: mysql:8.0.19
    environment:
      - TZ=${TZ}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    privileged: true
    # 挂载到 /var/lib/mysql 目录
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend
    restart: always

  mysql-manage:
    image: phpmyadmin/phpmyadmin
    environment:
      - TZ=${TZ}
      - PMA_ARBITRARY=1
      - MYSQL_USER=${MYSQL_MANAGE_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_MANAGE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_MANAGE_ROOT_PASSWORD}
      - PMA_HOST=${MYSQL_MANAGE_CONNECT_HOST}
      - PMA_PORT=${MYSQL_MANAGE_CONNECT_PORT}
    # 设置容器 80 端口映射指定宿主机端口（1000），用于宿主机访问可视化 web
    ports:
      - "${MYSQL_MANAGE_PORT}:80"
    # 依赖容器，在 Mysql 服务容器启动后启动
    depends_on:
      - mysql
    networks:
      - backend
    restart: always
