package e

// 定义错误码类型
type ErrorCode int

// 成功码为 0
const (
	SUCCESS = 0
)

// 其他为错误码
const (
	// 基础错误码
	ERROR_BASE      = 10000
	ERROR_EXCEPTION = 10001

	// 数据库错误 11000-11999
	ERROR_DB_BASE   = ERROR_BASE + 1000
	ERROR_DB_CREATE = ERROR_DB_BASE + 1

	// 鉴权错误 12000-12999
	ERROR_AUTH_BASE = ERROR_BASE + 2000
	ERROR_AUTH_FAIL = ERROR_AUTH_BASE + 1

	// 参数错误 13000-13999
	ERROR_PARAM_BASE    = ERROR_BASE + 3000
	ERROR_PARAM_INVALID = ERROR_PARAM_BASE + 1

	// 用户类错误 15000 ~ 15999
	ERROR_USER_BASE          = ERROR_BASE + 5000
	ERROR_USER_EXIST         = ERROR_USER_BASE + 1
	ERROR_USER_NOT_FOUND     = ERROR_USER_BASE + 2
	ERROR_USER_PASSWORD      = ERROR_USER_BASE + 3
	ERROR_USER_SET_PASSWORD  = ERROR_USER_BASE + 4
	ERROR_PASSWORD_NOT_MATCH = ERROR_USER_BASE + 5
)
