basePath: /api/v1
definitions:
  schema.Login:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  schema.OrderCreate:
    properties:
      name:
        type: string
      user_id:
        type: integer
    type: object
  schema.OrderDetail:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  schema.OrderList:
    properties:
      orders:
        items:
          $ref: '#/definitions/schema.OrderDetail'
        type: array
    type: object
  schema.PageInfo:
    properties:
      limit:
        type: integer
      offset:
        type: integer
      total:
        type: integer
    type: object
  schema.Register:
    properties:
      password:
        type: string
      password_confirm:
        type: string
      username:
        type: string
    required:
    - password
    - password_confirm
    - username
    type: object
  schema.Response:
    properties:
      code:
        type: integer
      data:
        type: any
      message:
        type: string
    type: object
  schema.ResponseWithPageInfo:
    properties:
      code:
        type: integer
      data:
        type: any
      message:
        type: string
      page_info:
        $ref: '#/definitions/schema.PageInfo'
    type: object
  schema.UserDetail:
    properties:
      created_at:
        type: string
      id:
        type: integer
      updated_at:
        type: string
      username:
        type: string
    type: object
  schema.UserDetailWithToken:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/schema.UserDetail'
    type: object
  schema.UserOrderCreate:
    properties:
      name:
        type: string
    required:
    - name
    type: object
host: localhost:8080
info:
  contact: {}
  description: 详情见源码地址：https://github.com/fmw666/microservice-code-sample/tree/monolithic-app.
  title: 单体应用 swagger-ui API 文档
  version: "1.0"
paths:
  /orders:
    get:
      consumes:
      - application/json
      description: Order 服务中提供的获取订单列表服务
      parameters:
      - description: 用户 id
        in: query
        name: user_id
        type: integer
      - description: 偏移量
        in: query
        name: offset
        type: integer
      - description: 限制数量
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"data":{},"message":""}'
          schema:
            allOf:
            - $ref: '#/definitions/schema.ResponseWithPageInfo'
            - properties:
                data:
                  $ref: '#/definitions/schema.OrderList'
              type: object
      summary: 获取订单列表
      tags:
      - Order 服务
    post:
      consumes:
      - application/json
      description: Order 服务中提供的创建订单服务
      parameters:
      - description: 订单
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/schema.OrderCreate'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"data":{},"message":""}'
          schema:
            allOf:
            - $ref: '#/definitions/schema.Response'
            - properties:
                data:
                  $ref: '#/definitions/schema.OrderDetail'
              type: object
      summary: 创建订单
      tags:
      - Order 服务
  /user/login:
    post:
      consumes:
      - application/json
      description: User 服务中提供的用户登录服务
      parameters:
      - description: 登录
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.Login'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"data":{},"message":""}'
          schema:
            allOf:
            - $ref: '#/definitions/schema.Response'
            - properties:
                data:
                  $ref: '#/definitions/schema.UserDetailWithToken'
              type: object
      summary: 用户登录
      tags:
      - User 服务
  /user/orders:
    get:
      consumes:
      - application/json
      description: User 服务中提供的用户订单列表服务
      parameters:
      - description: Offset
        in: query
        name: offset
        type: integer
      - description: Limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"data":{},"message":""}'
          schema:
            allOf:
            - $ref: '#/definitions/schema.ResponseWithPageInfo'
            - properties:
                data:
                  $ref: '#/definitions/schema.OrderList'
              type: object
      security:
      - ApiKeyAuth: []
      - BasicAuth: []
      summary: 用户订单列表
      tags:
      - User 服务
    post:
      consumes:
      - application/json
      description: User 服务中提供的用户创建订单服务
      parameters:
      - description: 订单
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.UserOrderCreate'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"data":{},"message":""}'
          schema:
            allOf:
            - $ref: '#/definitions/schema.Response'
            - properties:
                data:
                  $ref: '#/definitions/schema.OrderDetail'
              type: object
      security:
      - ApiKeyAuth: []
      - BasicAuth: []
      summary: 用户创建订单
      tags:
      - User 服务
  /user/register:
    post:
      consumes:
      - application/json
      description: User 服务中提供的用户注册服务
      parameters:
      - description: 注册
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.Register'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"data":{},"message":""}'
          schema:
            allOf:
            - $ref: '#/definitions/schema.Response'
            - properties:
                data:
                  $ref: '#/definitions/schema.UserDetailWithToken'
              type: object
      summary: 用户注册
      tags:
      - User 服务
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
